**

!frontend/
frontend/*
!frontend/lib/
!frontend/lib/**
!frontend/web/
!frontend/web/**
!frontend/assets/
!frontend/assets/**
!frontend/pubspec.yaml
!frontend/pubspec.lock
!frontend/l10n.yaml
!frontend/analysis_options.yaml

!deploy/
deploy/*
!deploy/prod/
deploy/prod/*
!deploy/prod/nginx/
!deploy/prod/nginx/**
